[workspace]
name = "pixi_ros2"
version = "0.1.0"
description = "Add a short description here"
authors = ["Miguel Villa Floran <miguel.villafloran@gmail.com>"]
channels = ["robostack-humble", "conda-forge"]
platforms = ["linux-64", "win-64"]

[tasks]
graph = "ros2 run rqt_graph rqt_graph"
sim = "ros2 run turtlesim turtlesim_node"
build = "colcon build --symlink-install"
hello = "ros2 run my_package my_node"

[dependencies]
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
ros-humble-desktop = ">=0.10.0,<0.11"
ros-humble-turtlesim = ">=1.4.2,<2"
ros-humble-rqt-graph = ">=1.3.1,<2"

[activation]
scripts = ["install/setup.sh"]
[target.win-64.activation]
scripts = ["install/setup.bat"]
