[workspace]
name = "pixi_ros2"
version = "0.1.0"
description = "Add a short description here"
authors = ["Miguel Villa Floran <miguel.villafloran@gmail.com>"]
channels = ["robostack-humble", "conda-forge"]
platforms = ["linux-64"]

[tasks]
graph = "bash -c 'source install/setup.sh && ros2_graph /talker /listener -o ./src/chatter_diagram.md'"
sim = "ros2 run turtlesim turtlesim_node"
build = { cmd = "colcon build --symlink-install", inputs = ["src"] }
talker = { cmd = "bash -c 'source install/setup.sh && ros2 run my_package talker'", depends-on = [
  "build",
] }
listener = { cmd = "bash -c 'source install/setup.sh && ros2 run my_package listener'", depends-on = [
  "build",
] }
squared = { cmd = "bash -c 'source install/setup.sh && ros2 run my_package squared'", depends-on = [
  "build",
] }

[dependencies]
pre-commit = ">=4.3.0,<5"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
ros-humble-desktop = ">=0.10.0,<0.11"
ros-humble-turtlesim = ">=1.4.2,<2"
ros-humble-foxglove-bridge = ">=0.8.5,<0.9"
ros-humble-rosbag2-storage-mcap = ">=0.15.14,<0.16"

[pypi-dependencies]
ros2-graph = "*"
